name: Android-x86 VM + RustDesk + Tailscale

on:
  workflow_dispatch:
    inputs:
      runtime_minutes:
        description: "How long to keep VM alive (minutes)"
        required: false
        default: "60"
      ts_authkey:
        description: "Tailscale Auth Key (device admin)"
        required: true

jobs:
  android_vm:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y qemu-system-x86 adb curl unzip wget python3 python3-pip

      - name: Download Android-x86 ISO
        run: |
          mkdir -p $HOME/android
          cd $HOME/android
          wget -O android.iso https://osdn.net/projects/android-x86/downloads/72067/android-x86_64-9.0-r2.iso
          qemu-img create -f qcow2 android_disk.qcow2 8G

      - name: Start Android-x86 VM (VNC internal)
        run: |
          cd $HOME/android
          qemu-system-x86_64 \
            -m 2048 \
            -smp 2 \
            -boot d \
            -cdrom android.iso \
            -hda android_disk.qcow2 \
            -net nic -net user,hostfwd=tcp::5555-:5555 \
            -enable-kvm \
            -vnc 0.0.0.0:1 \
            -daemonize
          echo "VM started. Waiting 90s for boot..."
          sleep 90

      - name: Download Tailscale APK
        run: |
          mkdir -p $HOME/android/apks
          cd $HOME/android/apks
          wget -O tailscale.apk https://pkgs.tailscale.com/stable/tailscale_1.82.0.apk

      - name: Download RustDesk APK
        run: |
          cd $HOME/android/apks
          wget -O rustdesk.apk https://github.com/rustdesk/rustdesk/releases/download/1.3.1/rustdesk-1.3.1.apk

      - name: Install APKs via ADB
        run: |
          export ANDROID_HOME=$HOME/android
          adb connect localhost:5555
          adb install -r $HOME/android/apks/tailscale.apk
          adb install -r $HOME/android/apks/rustdesk.apk

      - name: Start Tailscale on Android-x86
        run: |
          adb shell am start -n com.tailscale.ipn/.MainActivity
          adb shell "su -c 'tailscale up --authkey=${{ inputs.ts_authkey }} --accept-routes --hostname=android-vm-github'"
          sleep 20
          IP=$(adb shell "ip addr show tun0 | grep 'inet ' | awk '{print \$2}' | cut -d/ -f1")
          echo "TAILSCALE_IP=$IP" >> $GITHUB_ENV
          echo "Tailscale IP: $IP"

      - name: Launch RustDesk (show ID)
        run: |
          adb shell am start -n "app.rustdesk/.MainActivity"
          sleep 10
          # RustDesk ID is visible in UI; optionally use automation to pull ID if needed
          echo "RustDesk should now be running inside Android VM"

      - name: Keep VM alive
        run: |
          RUNTIME=${{ inputs.runtime_minutes }}
          END=$(( $(date +%s) + RUNTIME*60 ))
          while [ $(date +%s) -lt $END ]; do
            echo "VM alive: $(date) | Tailscale IP: ${{ env.TAILSCALE_IP }}"
            sleep 60
          done
