name: Android 12 RDP via Tailscale

on:
  workflow_dispatch:

jobs:
  android:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y wget curl unzip openjdk-11-jdk xvfb x11vnc fluxbox

      - name: Install Android SDK
        run: |
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O sdk.zip
          mkdir android-sdk
          unzip sdk.zip -d android-sdk
          yes | android-sdk/cmdline-tools/bin/sdkmanager --licenses
          android-sdk/cmdline-tools/bin/sdkmanager "platform-tools" "emulator" "platforms;android-31" "system-images;android-31;google_apis;x86_64"

      - name: Create Android 12 AVD
        run: |
          echo "no" | android-sdk/cmdline-tools/bin/avdmanager create avd -n android12 -k "system-images;android-31;google_apis;x86_64"

      - name: Start Emulator Headless
        run: |
          nohup android-sdk/emulator/emulator -avd android12 -no-window -no-audio -gpu swiftshader_indirect &
          sleep 60

      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up --authkey=tskey-auth-kk5XXvZJFA11CNTRL-vCh5MqGZeSFr9CnjZ4FdSFRsz4Q7vsL6 --hostname github-android

      - name: Start Desktop + VNC
        run: |
          Xvfb :1 -screen 0 1280x720x16 &
          export DISPLAY=:1
          fluxbox &
          x11vnc -display :1 -nopw -forever -shared &

      - name: Keep Alive
        run: sleep 6h
